### ISSUE TITLE
docker build  of leaning experiment hangs at step 9/26

### ISSUE THREAD

**Issue by TommasoBendinelli** [yordanh/spatial_relations_experiments#1]
I am using Docker on a Windows 10 machine. Unfortunately the build stops at step 9 (of 26). It states "done" and then does not go further. 
So it stops at step "USER yordan"

**Comment by TommasoBendinelli** [comment]
It took really long time but eventually got further, the process of removing intermediate container is really slow.

**Comment by yordanh** [comment]
I tidied up the docker files for the learning experiments - can pull.

It does hang for me as well there but not for much - approx a minute. You can tell docker not to remove images by adding `--rm=false` to the build command in the Makefile. Alternatively wait a bit as it would only happen the first time you build.

**Comment by TommasoBendinelli** [comment]
Thank you for rapid answer and for the amazing paper!
