### ISSUE TITLE
How to run the code and minor issues

### ISSUE THREAD

**Issue by TommasoBendinelli** [yordanh/spatial_relations_experiments#2]
Hello, 
I am trying to run the code, but I am encountering difficulties. 
Particularly I don't get which files are important and which are not. 
I read me on how execute the code would be really useful

Also I am trying to run some scripts but I have found the following issues: 
-in eval_trained_model net_200x200 is important while there is no file with that name (there exists a file name net_128x128_mvae. 
-same thing for data_generator  (exist a file called data_generator_mvae) 
-cannot import config_parser.

I have installed the docker container and running the code through the docker.

Have a great day

**Comment by yordanh** [comment]
Hi, 
yes, there were a few redundant files that made it through without me noticing (now gone). I also went through the files for training the model on the photoreal data (_net_128x128..., data_generator_mvae, train_mvae and run_experiments_mvae) and cleaned the redundant comments which should make them more readable. 

Added a README file on how to train the model with different params which can be specified in the script:
`python src/run_experiments_mvae.py.` 

The data you can find [here](https://sites.google.com/view/explain-n-repeat) (last of the 4 links) with a README of its own. Just unzip next to scr/ and docker/

The evaluation for the _explaining_ experiments, with a trained model, I have in a separate notebook, not as scripts, but it's not in a state for release yet. Same for the robot-related experiments. Can ping you once it's done. 
Depending on which part of the methods or the data you need I might prioritise refactoring and sharing it first.

**Comment by TommasoBendinelli** [comment]
Thank you for your quick answer. I am currently doing my Master Thesis, and I found your paper really nice and in direction on which my supervisor and I want to go (Learning from demonstration complicated task (i.e. tasks that can decomposed in elementary primitives such as pick and place) while providing an Human Readable output. I am studying deeply your paper and related literature that you cite (currently I understand how you use the Variational Convolutional Neural Network to get a disentangle representation of inter-object relationship, I still do not grasp how you can use this representation for the high level control of the robot).

The link that you post I could find the clevr-dataset, but unfortunately I could not find "robot_dataset" (i.e. the data needed for  running all the _robot python files).

Any new release of the code/datasets or just tips and useful resources is more than welcome.
Keep up the great work and have a nice evening.

**Comment by yordanh** [comment]
Hi Tommaso,
I've sent you a link with the dataset regarding the robot experiments - both for training the relational embeddings and the end effector regression.
