### ISSUE TITLE
Chainer version for runnning the code

### ISSUE THREAD

**Issue by TommasoBendinelli** [yordanh/spatial_relations_experiments#3]
I think there is an issue between the chained version and the python version: when building the dockerfile you get the last version of chainer (now 7.0) but it is incompatible with python 2.x. Should I use chainer 6.0 ?

**Comment by yordanh** [comment]
When writing the paper I think I used 4.5.0. I currently have a built container with 6.5.0 (I built it before they released 7.0) and it seems to be running fine.
